### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [agallant121/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [ ] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [ ] The four methods I chose for **Class #1** represent behaviors or actions.
- [ ] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [ ] I listed the values for each attribute of this object. 
- [ ] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [ ] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [ ] The four methods I chose for **Class #2** represent behaviors or actions.
- [ ] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [ ] I listed the values for each attribute of this object. 
- [ ] I listed the results of each method for this object. 
- [x] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready

**Comment by damwhit** [comment]
@agallant121  good work on the top down design portion of this. We'd like you to do more on the classes section, because you used essentially the same class in both class files and there were some other inconsistencies. To do so:

* [x] - Create a class_3.txt file - pick one from `chair`, `table`, or `refrigerator` for this class
  * [x] - make sure that your format matches this file that is linked in session 5: https://gist.github.com/rwarbelow/aa554ea9091efe6ed1a8ae66e95430a0 (keep it simple)
  * [x] - make sure that your data types are consistent. (ie. I found it quite confusing in your class_1.txt file where you said personnel was strings, and then you used an array later on in your method) - again, keep it simple. Probably stick with the more primitive data types (no arrays or objects)
* [x] - create a `class_3_example_object.txt` file that correspond the class file. 
  * [x] - make sure that it matches this format: https://gist.github.com/rwarbelow/2639de952d5cc4e862662d04dfef2a64
  * [x] - make sure that the attributes start out with certain values, and the methods show how those values change or what is returned from the method.
